[package]
name = "planet-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "common"
crate-type = ["staticlib", "rlib"]

[dependencies]
serde = "*"
serde_json = "*"